<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTa0Jq9n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTa0Jq9n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTa0Jq9n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTa0Jq9n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTa0Jq9n\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ta0Jq9n',
    'container.build_id' => 'e7c41493',
    'container.build_time' => 1695129137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTa0Jq9n');
